//SceneTrackFbx,0,3,290
#ifndef SCENETRACKFBX_VERSION_H
#define SCENETRACKFBX_VERSION_H
#define SCENETRACKFBX_VERSION_NAME "SceneTrackFbx"
#define SCENETRACKFBX_VERSION_MAJOR 0
#define SCENETRACKFBX_VERSION_MINOR 3
#define SCENETRACKFBX_VERSION_BUILD 290
#define SCENETRACKFBX_VERSION_STR "SceneTrackFbx 0.3.290"
#endif
