//SceneTrackMidi,0,3,132
#ifndef SCENETRACKMIDI_VERSION_H
#define SCENETRACKMIDI_VERSION_H
#define SCENETRACKMIDI_VERSION_NAME "SceneTrackMidi"
#define SCENETRACKMIDI_VERSION_MAJOR 0
#define SCENETRACKMIDI_VERSION_MINOR 3
#define SCENETRACKMIDI_VERSION_BUILD 132
#define SCENETRACKMIDI_VERSION_STR "SceneTrackMidi 0.3.132"
#endif
