//SceneTrackMidi,0,3,48
#ifndef SCENETRACKMIDI_VERSION_H
#define SCENETRACKMIDI_VERSION_H
#define SCENETRACKMIDI_VERSION_NAME "SceneTrackMidi"
#define SCENETRACKMIDI_VERSION_MAJOR 0
#define SCENETRACKMIDI_VERSION_MINOR 3
#define SCENETRACKMIDI_VERSION_BUILD 48
#define SCENETRACKMIDI_VERSION_STR "SceneTrackMidi 0.3.48"
#endif
