//SceneTrack,0,3,356
#ifndef SCENETRACK_VERSION_H
#define SCENETRACK_VERSION_H
#define SCENETRACK_VERSION_NAME "SceneTrack"
#define SCENETRACK_VERSION_MAJOR 0
#define SCENETRACK_VERSION_MINOR 3
#define SCENETRACK_VERSION_BUILD 356
#define SCENETRACK_VERSION_STR "SceneTrack 0.3.356"
#endif
