//SceneTrackVideo,0,3,63
#ifndef SCENETRACKVIDEO_VERSION_H
#define SCENETRACKVIDEO_VERSION_H
#define SCENETRACKVIDEO_VERSION_NAME "SceneTrackVideo"
#define SCENETRACKVIDEO_VERSION_MAJOR 0
#define SCENETRACKVIDEO_VERSION_MINOR 3
#define SCENETRACKVIDEO_VERSION_BUILD 63
#define SCENETRACKVIDEO_VERSION_STR "SceneTrackVideo 0.3.63"
#endif
